/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.Cancion;
import BackEnd.Pista;
import BackEnd.RepKaraoke;
import BackEnd.Video;
import javax.swing.JOptionPane;

/**
 *
 * @author isabe
 */
public class AgregarCancion extends javax.swing.JFrame {

    RepKaraoke App;
    Cancion _Nueva;

    /**
     * Creates new form NewJFrame
     */
    public AgregarCancion(RepKaraoke app) {
        initComponents();
        setResizable(false);
        App = app;
        _Nueva = null;
    }

    AgregarCancion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoCancion = new javax.swing.ButtonGroup();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Artista = new javax.swing.JTextField();
        Album = new javax.swing.JTextField();
        Titulo = new javax.swing.JTextField();
        Minutos = new javax.swing.JTextField();
        Segundos = new javax.swing.JTextField();
        Track = new javax.swing.JTextField();
        CancionBox = new javax.swing.JCheckBox();
        VideoBox = new javax.swing.JCheckBox();
        PistaBox = new javax.swing.JCheckBox();
        FormatoVideo = new javax.swing.JTextField();
        ArchivoLetra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Artista.setBorder(javax.swing.BorderFactory.createTitledBorder("Artista"));

        Album.setBorder(javax.swing.BorderFactory.createTitledBorder("Album"));

        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        Minutos.setBorder(javax.swing.BorderFactory.createTitledBorder("Min"));
        Minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutosActionPerformed(evt);
            }
        });

        Segundos.setBorder(javax.swing.BorderFactory.createTitledBorder("Seg"));
        Segundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundosActionPerformed(evt);
            }
        });

        Track.setBorder(javax.swing.BorderFactory.createTitledBorder("Track"));

        TipoCancion.add(CancionBox);
        CancionBox.setSelected(true);
        CancionBox.setText("Cancion");
        CancionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancionBoxActionPerformed(evt);
            }
        });

        TipoCancion.add(VideoBox);
        VideoBox.setText("Video");
        VideoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoBoxActionPerformed(evt);
            }
        });

        TipoCancion.add(PistaBox);
        PistaBox.setText("Pista");
        PistaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PistaBoxActionPerformed(evt);
            }
        });

        FormatoVideo.setEditable(false);
        FormatoVideo.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato Video"));
        FormatoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatoVideoActionPerformed(evt);
            }
        });

        ArchivoLetra.setEditable(false);
        ArchivoLetra.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivo de Letras\n"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Artista, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Album)
            .addComponent(Titulo)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Track))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CancionBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(VideoBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormatoVideo))
            .addGroup(layout.createSequentialGroup()
                .addComponent(PistaBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArchivoLetra))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Track, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancionBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VideoBox)
                    .addComponent(FormatoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PistaBox)
                    .addComponent(ArchivoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundosActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Artista.setText("");
        Album.setText("");
        Titulo.setText("");
        Minutos.setText("");
        Segundos.setText("");
        Track.setText("");
        FormatoVideo.setText("");
        ArchivoLetra.setText("");
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        String artista;
        String album;
        String titulo;
        int min;
        int seg;
        int track;
        String formato;
        String archivo;
        if (CancionBox.isSelected()) {
            if (!Artista.getText().isEmpty() && !Album.getText().isEmpty() && !Titulo.getText().isEmpty()
                    || !Minutos.getText().isEmpty() && !Segundos.getText().isEmpty() && !Track.getText().isEmpty()) {
                try {
                    artista = Artista.getText();
                    album = Album.getText();
                    titulo = Titulo.getText();
                    min = Integer.parseInt(Minutos.getText());
                    seg = Integer.parseInt(Segundos.getText());
                    track = Integer.parseInt(Track.getText());
                    if (artista.isEmpty() || album.isEmpty() || titulo.isEmpty() || min > 99 || seg > 59) {
                        JOptionPane.showMessageDialog(null, "Verifique los campos");
                    } else {
                        _Nueva = new Cancion(artista, album, titulo, (min * 60 + seg), track);
                        App.getBiblioteca().InsertarFinal(_Nueva);
                        App.getGUI().Modelo.addElement(_Nueva.getArtista() + "\t" + _Nueva.getTitulo() + "\t" + _Nueva.getAlbum() + "\t" + _Nueva.getTrack() + "\t" + App.formatoTiempo(_Nueva.getDuracion()));
                        App.getTitulos().Insertar(App.getTitulos().getRaiz(), _Nueva);
                        App.getArtistas().insertarCancion(_Nueva);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Nueva Cancion agregada");
                    }

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Verifique los campos");
                }
            }
        } else if (VideoBox.isSelected()) {
            if (!Artista.getText().isEmpty() && !Album.getText().isEmpty() && !Titulo.getText().isEmpty()
                    && !Minutos.getText().isEmpty() && !Segundos.getText().isEmpty() && !Track.getText().isEmpty()
                    && !FormatoVideo.getText().isEmpty()) {
                try {
                    artista = Artista.getText();
                    album = Album.getText();
                    titulo = Titulo.getText();
                    min = Integer.parseInt(Minutos.getText());
                    seg = Integer.parseInt(Segundos.getText());
                    track = Integer.parseInt(Track.getText());
                    formato = FormatoVideo.getText();
                    if (artista.isEmpty() || album.isEmpty() || titulo.isEmpty() || min > 99 || seg > 59) {
                        JOptionPane.showMessageDialog(null, "Verifique los campos");
                    } else {
                        _Nueva = new Video(artista, album, titulo, (min * 60 + seg), track, formato);
                        App.getBiblioteca().InsertarFinal(_Nueva);
                        App.getGUI().Modelo.addElement(_Nueva.getArtista() + "\t" + _Nueva.getTitulo() + "\t" + _Nueva.getAlbum() + "\t" + _Nueva.getTrack() + "\t" + App.formatoTiempo(_Nueva.getDuracion()));
                        App.getTitulos().Insertar(App.getTitulos().getRaiz(), _Nueva);
                        App.getArtistas().insertarCancion(_Nueva);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Nueva Cancion agregada");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Verifique los campos");
                }
            }
        } else if (PistaBox.isSelected()) {
            if (!Artista.getText().isEmpty() && !Album.getText().isEmpty() && !Titulo.getText().isEmpty()
                    && !Minutos.getText().isEmpty() && !Segundos.getText().isEmpty() && !Track.getText().isEmpty()
                    && !ArchivoLetra.getText().isEmpty()) {
                try {
                    artista = Artista.getText();
                    album = Album.getText();
                    titulo = Titulo.getText();
                    min = Integer.parseInt(Minutos.getText());
                    seg = Integer.parseInt(Segundos.getText());
                    track = Integer.parseInt(Track.getText());
                    archivo = ArchivoLetra.getText();
                    if (artista.isEmpty() || album.isEmpty() || titulo.isEmpty() || min > 99 || seg > 59) {
                        JOptionPane.showMessageDialog(null, "Verifique los campos");
                    } else {
                        _Nueva = new Pista(artista, album, titulo, (min * 60 + seg), track, archivo);
                        App.getBiblioteca().InsertarFinal(_Nueva);
                        App.getGUI().Modelo.addElement(_Nueva.getArtista() + " - " + _Nueva.getTitulo() + " - " + _Nueva.getAlbum() + " - " + _Nueva.getTrack() + " - " + App.formatoTiempo(_Nueva.getDuracion()));
                        App.getTitulos().Insertar(App.getTitulos().getRaiz(), _Nueva);
                        App.getArtistas().insertarCancion(_Nueva);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Nueva Cancion agregada");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Verifique los campos");
                }
            }
        }
        App.escribirData(App.getBiblioteca());
        Artista.setText("");
        Album.setText("");
        Titulo.setText("");
        Minutos.setText("");
        Segundos.setText("");
        Track.setText("");
        FormatoVideo.setText("");
        ArchivoLetra.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void VideoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoBoxActionPerformed
        FormatoVideo.setEditable(VideoBox.isSelected());
        ArchivoLetra.setEditable(PistaBox.isSelected());
        if (!ArchivoLetra.isEditable()) {
            ArchivoLetra.setText("");
        }
        if (!FormatoVideo.isEditable()) {
            FormatoVideo.setText("");
        }
    }//GEN-LAST:event_VideoBoxActionPerformed

    private void PistaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PistaBoxActionPerformed
        ArchivoLetra.setEditable(PistaBox.isSelected());
        FormatoVideo.setEditable(VideoBox.isSelected());
        if (!ArchivoLetra.isEditable()) {
            ArchivoLetra.setText("");
        }
        if (!FormatoVideo.isEditable()) {
            FormatoVideo.setText("");
        }
    }//GEN-LAST:event_PistaBoxActionPerformed

    private void FormatoVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatoVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormatoVideoActionPerformed

    private void CancionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancionBoxActionPerformed
        ArchivoLetra.setEditable(PistaBox.isSelected());
        FormatoVideo.setEditable(VideoBox.isSelected());
        if (!ArchivoLetra.isEditable()) {
            ArchivoLetra.setText("");
        }
        if (!FormatoVideo.isEditable()) {
            FormatoVideo.setText("");
        }
    }//GEN-LAST:event_CancionBoxActionPerformed

    private void MinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutosActionPerformed

    }//GEN-LAST:event_MinutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Album;
    private javax.swing.JTextField ArchivoLetra;
    private javax.swing.JTextField Artista;
    private javax.swing.JButton Cancelar;
    private javax.swing.JCheckBox CancionBox;
    private javax.swing.JTextField FormatoVideo;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Minutos;
    private javax.swing.JCheckBox PistaBox;
    private javax.swing.JTextField Segundos;
    private javax.swing.ButtonGroup TipoCancion;
    private javax.swing.JTextField Titulo;
    private javax.swing.JTextField Track;
    private javax.swing.JCheckBox VideoBox;
    // End of variables declaration//GEN-END:variables
}
