/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.Pista;
import java.awt.Color;
import BackEnd.RepKaraoke;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author isabe
 */
public class Reproductor extends javax.swing.JFrame{

    public RepKaraoke _App;
    boolean Reset;
    boolean Running;
    
    /**
     * Creates new form sdss
     */
    public Reproductor() {
        initComponents();
        Reset = false;
        getContentPane().setBackground(Color.DARK_GRAY);
    }

    public Reproductor(RepKaraoke _App) {
        this._App = _App;
        initComponents();
        setResizable(false);
        getContentPane().setBackground(Color.DARK_GRAY);
    }

    public JLabel getArtista() {
        return Artista;
    }

    public void setArtista(JLabel Artista) {
        this.Artista = Artista;
    }

    public JLabel getTitulo() {
        return Titulo;
    }

    public void setTitulo(JLabel Titulo) {
        this.Titulo = Titulo;
    }

    //Método que llamaremos desde nuestro botón
    private void Reproducir() {
        //Creamos un Thread para mejorar el ejemplo
        Thread t;
        //Inicializamos
        t = new Thread(new Runnable() {
            //Implementamos el método run()
            @Override
            public void run() {
                //Permite mostrar el valor del progreso
                ProgresoDuracion.setStringPainted(true);
                //Asigna el valor de la duracion de la cancion como valor maximo al progress bar
                ProgresoDuracion.setMaximum(_App.getReproduccion().getCabeza().getDuracion());
                float x = 0;
                String[] letras = new String[_App.getReproduccion().getCabeza().getDuracion() + 1];
                if (_App.getReproduccion().getCabeza() instanceof Pista) {
                    try {
                        letras = ((Pista) _App.getReproduccion().getCabeza()).leerPista(_App.getReproduccion().getCabeza().getDuracion());
                        /*   if(NoArchivo){
                                                Letras.setText("No se encontro el archivo de letras");
                        }*/
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "No se encontro el archivo de la letra.\nPor favor, lea el readme adjunto en la carpeta del programa.");
                    }
                }
                //Utilizamos un while para emular el valor mínimo y máximo
                //En este caso 0 - y la duracion de la cancion
                while (_App.getReproduccion().getCabeza() != null && x <= _App.getReproduccion().getCabeza().getDuracion() + 1 && !Reset) {
                    //Asignamos valor a nuestro JProgressBar por cada siclo del bucle
                    if (_App.getReproduccion().getCabeza() instanceof Pista) {
                        //arrojamos la letra de la cancion en el TextPanel
                        Letras.setText(letras[(int) x]);
                    }
                    //variable que nos dice si el thread esta running o no
                    Running = true;
                    // asigna la barra de progreso
                    ProgresoDuracion.setValue((int) x);
                    ProgresoDuracion.setString(_App.formatoTiempo((int) x));
                    try {
                        Thread.sleep(1); //sleep por un milisegundo
                    } catch (InterruptedException e) {
                    }
                    //Se incrementa el valor de x por cada milisengundo
                    x += 0.001;
                }
            }
        });
        //Se ejecuta el Thread
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Proximo = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        SacarDeLista = new javax.swing.JButton();
        Repeat = new javax.swing.JCheckBox();
        Anterior = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Artista = new javax.swing.JLabel();
        Letras = new javax.swing.JLabel();
        ProgresoDuracion = new javax.swing.JProgressBar();
        Play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Proximo-Fijo.png"))); // NOI18N
        Proximo.setBorder(null);
        Proximo.setBorderPainted(false);
        Proximo.setContentAreaFilled(false);
        Proximo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Proximo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Proximo-Pressed.png"))); // NOI18N
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Menu-Fijo.png"))); // NOI18N
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setContentAreaFilled(false);
        Menu.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Menu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Menu-Pressed.png"))); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        Menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuKeyPressed(evt);
            }
        });

        SacarDeLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Eliminar-Fijo.png"))); // NOI18N
        SacarDeLista.setBorder(null);
        SacarDeLista.setBorderPainted(false);
        SacarDeLista.setContentAreaFilled(false);
        SacarDeLista.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SacarDeLista.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Eliminar-Pressed.png"))); // NOI18N
        SacarDeLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacarDeListaActionPerformed(evt);
            }
        });

        Repeat.setBorder(null);
        Repeat.setContentAreaFilled(false);
        Repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Repeat-Unchecked.png"))); // NOI18N
        Repeat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Repeat-Checked.png"))); // NOI18N
        Repeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatActionPerformed(evt);
            }
        });

        Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Anterior-Fijo.png"))); // NOI18N
        Anterior.setBorder(null);
        Anterior.setBorderPainted(false);
        Anterior.setContentAreaFilled(false);
        Anterior.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Anterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Anterior-Pressed.png"))); // NOI18N
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Titulo.setBackground(new java.awt.Color(51, 51, 51));
        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Titulo Cancion");
        Titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Artista.setBackground(new java.awt.Color(0, 0, 0));
        Artista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Artista.setForeground(new java.awt.Color(255, 255, 255));
        Artista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Artista.setText("Artista");
        Artista.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Letras.setBackground(new java.awt.Color(0, 0, 0));
        Letras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Letras.setForeground(new java.awt.Color(255, 255, 255));
        Letras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ProgresoDuracion.setBackground(new java.awt.Color(51, 51, 51));
        ProgresoDuracion.setForeground(new java.awt.Color(204, 204, 204));
        ProgresoDuracion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ProgresoDuracion.setBorderPainted(false);
        ProgresoDuracion.setString("");

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Play-Fijo.png"))); // NOI18N
        Play.setBorder(null);
        Play.setBorderPainted(false);
        Play.setContentAreaFilled(false);
        Play.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/PngFiles/Boton-Play-Pressed.png"))); // NOI18N
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Artista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Letras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ProgresoDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Anterior)
                .addGap(18, 18, 18)
                .addComponent(Play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Repeat)
                .addGap(18, 18, 18)
                .addComponent(Proximo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SacarDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Letras, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgresoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Proximo)
                        .addComponent(Repeat))
                    .addComponent(Play)
                    .addComponent(Anterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addGap(4, 4, 4)
                .addComponent(Artista)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu)
                    .addComponent(SacarDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Reset = true;
        Running = false;
        ProgresoDuracion.setValue(0);
        ProgresoDuracion.setString(_App.formatoTiempo(0));
        _App.getReproduccion().Vaciar();
        dispose();
        _App.getGUI().setVisible(true);
        _App.getGUI().toFront();
        Letras.setText("");
        Repeat.setSelected(false);
    }//GEN-LAST:event_MenuActionPerformed

    private void SacarDeListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacarDeListaActionPerformed
        if (_App.getReproduccion().getCabeza() != _App.getReproduccion().getCola()) {
            Reset = true;
            Running = false;
            ProgresoDuracion.setValue(0);
            ProgresoDuracion.setString(_App.formatoTiempo(0));
            _App.getReproduccion().SacarCancion();
            _App.getReproduccion().Siguiente(Repeat.isSelected());
            Titulo.setText(_App.getReproduccion().getCabeza().getTitulo());
            Artista.setText(_App.getReproduccion().getCabeza().getArtista());
            Repeat.setSelected(false);
        } else {
            _App.getGUI().setVisible(true);
            this.dispose();
        }
        Letras.setText("");
    }//GEN-LAST:event_SacarDeListaActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        if (Running = true) {
            Reset = true;
            Running = false;
        }
        _App.getReproduccion().Anterior(Repeat.isSelected());
        ProgresoDuracion.setValue(0);
        ProgresoDuracion.setString(_App.formatoTiempo(0));
        Titulo.setText(_App.getReproduccion().getCabeza().getTitulo());
        Artista.setText(_App.getReproduccion().getCabeza().getArtista());
        Letras.setText("");
    }//GEN-LAST:event_AnteriorActionPerformed

    private void RepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatActionPerformed
    }//GEN-LAST:event_RepeatActionPerformed

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        Reset = true;
        Running = false;
        _App.getReproduccion().Siguiente(Repeat.isSelected());
        ProgresoDuracion.setValue(0);
        ProgresoDuracion.setString(_App.formatoTiempo(0));
        Titulo.setText(_App.getReproduccion().getCabeza().getTitulo());
        Artista.setText(_App.getReproduccion().getCabeza().getArtista());
        Letras.setText("");
    }//GEN-LAST:event_ProximoActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        if (!Running) {
            Reproducir();
        }
        Reset = false;
    }//GEN-LAST:event_PlayActionPerformed

    private void MenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuKeyPressed

    }//GEN-LAST:event_MenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Reproductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JLabel Artista;
    private javax.swing.JLabel Letras;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Play;
    private javax.swing.JProgressBar ProgresoDuracion;
    private javax.swing.JButton Proximo;
    private javax.swing.JCheckBox Repeat;
    private javax.swing.JButton SacarDeLista;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}